---
title: "論文圖表對應程式碼位置"
output: html_document
date: "2025-04-17"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 實證研究一：台灣十年期國債殖利率
#### 資料檔案及程式碼檔案相關說明：
1. 這筆實證研究的程式碼檔案為：台灣十年期國債殖利率.R
2. 這筆實證研究的資料檔為：台灣gdp_data.csv、台灣cpi_data.csv、台灣DGS10_data.csv
3. 程式碼執行順序：
- step 1：先執行第1-17行的程式碼，以載入套件
- step 2：再執行第20-709行程式碼
- step 3：在執行接下去第719-755行的程式碼前，我們需要先將第719-755行的程式碼，更改其「名稱」。（由於要避免十年期國債殖利率資料之每次補值的結果都不同，而導致的隨機性，所以我們需要重複執行10次的step2，並將其結果儲存下來。因此，每次執行完step2後，我們需要在執行第719-755行的程式碼前，先確認第719-755行的程式碼的名稱是否對應到執行次數，例如：第一次執行step2後，就需要將第719-755行程式碼中，所有關於「result_(1-10)」的名稱改為：result_1。第二次執行step2，就需要將第719-755行程式碼中，所有名稱改為：result_2。以此類推，執行到第10次的step2後，就需要將第719-755行程式碼中所有名稱改為：result_10。）
- step 4：最後再執行第762-786行程式碼，以印出最終的兩張RMSE圖。

#### 論文中的圖表程式碼位置說明：
1. 論文第12頁，表4-1：台灣 GDP、CPI 及十年期國債殖利率資料之敘述統計：
- 想得到GDP敘述統計：第20-51行程式碼
- 想得到CPI敘述統計：第53-83行程式碼
- 想得到十年期國債殖利率（補值前，原殖利率）敘述統計：第87-102行程式碼
- 想得到十年期國債殖利率（補值後，更新殖利率）敘述統計：再執行第105-175行程式碼

2. 論文第13頁，表4-2：台灣十年期國債殖利率資料的訓練與預測時間之區間切割
- 此為應變數y的時間切割：第259-282行程式碼（訓練區間為interest_rate_in_sample[[1]]至interest_rate_in_sample[[34]]、預測區間為interest_rate_out_of_sample[[1]]至interest_rate_out_of_sample[[34]]，其中預測區間僅採用每個interest_rate_out_of_sample的最後66個值）

3. 論文第16頁，表 4-3：線性插值模型中 GDP、CPI 與十年期國債殖利率資料之選取期間：
- GDP log difference選取時間：第621-637行程式碼
- CPI log difference選取時間：第642-656行程式碼
- 美國蘋果公司股票收盤價報酬率選取時間：第664-678行程式碼

4. 論文第16頁，表 4-4：利用線性插值模型預測台灣十年期國債殖利率之訓練與預測時間區間切割：
- 在程式碼第698行，for (i in 1:31)：共切成31個滾動視窗
- 第700行，split <- m_d * (50 + i - 1)：每個訓練區間是50季

5. 論文第16、17頁，表 4-5：線性插值模型中各變數於預測十年期國債殖利率時之資料使用期間：
- 第683-693行程式碼

6. 論文第17頁，圖 4-1：線性插值模型於預測國債殖利率的滾動視窗一之訓練期間與預測期間示意圖：
- 第697-709行程式碼

7. 論文第19頁，圖 4-2：十年期國債殖利率預測的平均 RMSE：
- 第778-786行程式碼

8. 論文第19頁，圖 4-3：十年期國債殖利率預測的平均 RMSE（僅 rr、ru、interest rate only 模型）：
- 第769-775行程式碼


## 實證研究二：美國蘋果公司股票持有一季收盤價報酬率
#### 資料檔案及程式碼檔案相關說明：
1. 這筆實證研究的程式碼檔案為：美國蘋果公司持有一季報酬率.R
2. 這筆實證研究的資料檔為：AAPL_data.RDS、cpi_data.xlsx、gdp_data.xlsx
3. 程式碼執行順序：
- step 1：先執行第1-18行的程式碼，以載入套件
- step 2：再執行第24-521行程式碼
- step 3：在執行接下去第531-567行的程式碼前，我們需要先將第531-567行的程式碼，更改其「名稱」。（由於要避免APPLE股價補值每次的結果都不同，而導致的隨機性，所以我們需要重複執行10次的step2，並將其結果儲存下來。因此，每次執行完step2後，我們需要再執行第531-567行的程式碼前，先確認第531-567行的程式碼的名稱是否對應到執行次數，例如：第一次執行step2後，就需要將第531-567行程式碼的所有關於「apple_result_(1-10)」名稱改為：apple_result_1。第二次執行step2，就需要將第531-567行程式碼的所有名稱改為：apple_result_2。以此類推至，執行到第10次的step2後，就需要將第531-567行程式碼的所有名稱改為：apple_result_10。）
- step 4：最後再執行第570-599行程式碼，以印出最終的兩張RMSE圖。

#### 論文中的圖表程式碼位置說明：
1. 論文第21頁，表4-6：美國 GDP、CPI 及蘋果公司股票收盤價敘述統計：
- 想得到美國蘋果公司股票收盤價（補值前，原收盤價）敘述統計：第29-39行程式碼
- 想得到美國蘋果公司股票收盤價（補值後，更新收盤價）敘述統計：再執行第47-115行程式碼
- 想得到CPI敘述統計：第129-155行程式碼
- 想得到GDP敘述統計：第159-179行程式碼

2. 論文第22頁，表4-7：蘋果公司股票持有一季收盤價的報酬率資料的訓練與預測時間之區間切割：
- 此為應變數y的時間切割：第261-284行程式碼（訓練區間為stock_price_in_sample[[2]]至stock_price_in_sample[[92]]、預測區間為stock_price_out_of_sample[[2]]至stock_price_out_of_sample[[92]]，其中預測區間僅採用每個stock_price_out_of_sample的最後66個值）

3. 論文第25頁，表 4-8：線性插值模型中 GDP、CPI及蘋果公司股價收盤價報酬率資料之選取期間：
- GDP log difference選取時間：第447-463行程式碼
- CPI percent change選取時間：第468-483行程式碼
- 美國蘋果公司股票收盤價報酬率選取時間：第487-489行程式碼

4. 論文第26頁，表 4-9：利用線性插值模型預測蘋果公司股票持有一季的收盤價報酬率之訓練及預測時間區間切割：
- 在程式碼第510行，for(i in 1:88)：共切成88個滾動視窗
- 第512行，split <- m_d * (60 + i - 1)：每個訓練區間是60季

5. 論文第26頁，表 4-10：線性插值模型中各變數於預測蘋果公司股票持有一季的收盤價報酬率之資料使用期間：
- 第493-504行程式碼

6. 論文第27頁，圖 4-4：線性插值模型於預測收盤價報酬率的滾動視窗一之訓練期間與預測期間示意圖：
- 第509-521行程式碼

7. 論文第28頁，圖 4-5：美國蘋果公司股票持有一季之收盤價報酬率預測的平均 RMSE：
- 第592-599行程式碼

8. 論文第29頁，圖 4-6：美國蘋果公司股票持有一季之收盤價報酬率的平均 RMSE（僅 rr、ru、stock price only 模型）：
- 第582-589行程式碼



